# Generated by Django 5.1.7 on 2025-03-10 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tc_app', '0002_membership'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='expiration_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='membership',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='membership',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
