# Generated by Django 5.1.7 on 2025-03-24 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tc_app', '0002_membership_end_date_membership_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='interests',
            field=models.TextField(blank=True, null=True),
        ),
    ]
