# Generated by Django 5.1.7 on 2025-03-10 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tc_app', '0004_event_module_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='interests',
            field=models.TextField(blank=True, default='[]'),
        ),
    ]
