# Generated by Django 5.1.7 on 2025-03-15 12:20

import django.contrib.auth.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tc_app', '0007_customuser_bio_customuser_phone_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={},
        ),
        migrations.AlterModelOptions(
            name='module',
            options={},
        ),
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RenameField(
            model_name='membership',
            old_name='join_date',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='testimonial',
            old_name='date_added',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='is_read',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_admin',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='event',
            name='capacity',
        ),
        migrations.RemoveField(
            model_name='event',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='expiration_date',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='interests',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='location',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='profile_image',
        ),
        migrations.RemoveField(
            model_name='membershiptype',
            name='features',
        ),
        migrations.RemoveField(
            model_name='module',
            name='content',
        ),
        migrations.RemoveField(
            model_name='module',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='module',
            name='order',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='is_featured',
        ),
        migrations.AddField(
            model_name='event',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('upcoming', 'Upcoming'), ('ongoing', 'Ongoing'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='upcoming', max_length=20),
        ),
        migrations.AddField(
            model_name='membership',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='membership',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='module',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='message',
            field=models.TextField(blank=True, default='No message provided', null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(blank=True, default='Anonymous', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='subject',
            field=models.CharField(blank=True, default='General Inquiry', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True, default='No description provided', null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(blank=True, default='TBD', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(blank=True, default='Untitled Event', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='membership',
            name='full_name',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='membership',
            name='membership_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tc_app.membershiptype'),
        ),
        migrations.AlterField(
            model_name='membershiptype',
            name='description',
            field=models.TextField(blank=True, default='Basic membership type', null=True),
        ),
        migrations.AlterField(
            model_name='membershiptype',
            name='name',
            field=models.CharField(blank=True, default='Basic', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='membershiptype',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='module',
            name='description',
            field=models.TextField(blank=True, default='No description provided', null=True),
        ),
        migrations.AlterField(
            model_name='module',
            name='title',
            field=models.CharField(blank=True, default='Untitled Module', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='content',
            field=models.TextField(blank=True, default='No content provided', null=True),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='name',
            field=models.CharField(blank=True, default='Anonymous', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='role',
            field=models.CharField(blank=True, default='Member', max_length=100, null=True),
        ),
    ]
