# Generated by Django 5.1.7 on 2025-03-11 17:21

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tc_app', '0008_alter_contact_options_alter_customuser_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='membershiptype',
            options={'ordering': ['order', 'price'], 'verbose_name': 'Membership Type', 'verbose_name_plural': 'Membership Types'},
        ),
        migrations.AddField(
            model_name='membership',
            name='expiration_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='membership',
            name='membership_type',
            field=models.CharField(choices=[('FREE', 'Free'), ('BASIC', 'Basic'), ('PREMIUM', 'Premium'), ('PRO', 'Professional')], default='FREE', max_length=10),
        ),
        migrations.AddField(
            model_name='membershiptype',
            name='code',
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
        migrations.AddField(
            model_name='membershiptype',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='membershiptype',
            name='duration_months',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='membershiptype',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='membershiptype',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='membershiptype',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='membershiptype',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='membershiptype',
            name='features',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='membershiptype',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='membershiptype',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.CreateModel(
            name='MembershipBenefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('icon', models.CharField(blank=True, default='fas fa-check', max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('order', models.PositiveIntegerField(default=0)),
                ('membership_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='benefits', to='tc_app.membershiptype')),
            ],
            options={
                'verbose_name': 'Membership Benefit',
                'verbose_name_plural': 'Membership Benefits',
                'ordering': ['order', 'name'],
            },
        ),
    ]
