# Generated by Django 5.1.7 on 2025-03-15 22:33

import django.db.models.deletion
import django.utils.timezone
import tc_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tc_app', '0009_eventbooking_moduleenrollment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='membership',
            options={'verbose_name_plural': 'Memberships'},
        ),
        migrations.RemoveField(
            model_name='membership',
            name='email',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='membership',
            name='end_date',
            field=models.DateTimeField(default=tc_app.models.get_default_end_date),
        ),
        migrations.AddField(
            model_name='membership',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='membershiptype',
            name='duration',
            field=models.IntegerField(default=1, help_text='Duration in months'),
        ),
        migrations.AddField(
            model_name='membershiptype',
            name='features',
            field=models.TextField(default='- Basic features\n- Standard support'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='membership',
            name='membership_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='tc_app.membershiptype'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='membershiptype',
            name='description',
            field=models.TextField(default='Standard membership package'),
        ),
        migrations.AlterField(
            model_name='membershiptype',
            name='name',
            field=models.CharField(default='Basic', max_length=100),
        ),
    ]
