# Generated by Django 5.1.7 on 2025-03-11 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tc_app', '0002_add_initial_memberships'),
        ('tc_app', '0009_alter_membershiptype_options_and_more'),
    ]

    operations = [
    ]
