# Generated by Django 5.1.7 on 2025-03-11 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tc_app', '0010_merge_20250311_2228'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='interests',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
