# Generated by Django 5.1.7 on 2025-03-11 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tc_app', '0011_membership_interests'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='membership',
            name='interests',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
