# Generated by Django 5.1.7 on 2025-03-15 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tc_app', '0012_alter_membershiptype_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='profile_image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='profile_images/'),
        ),
    ]
