# Generated by Django 5.1.7 on 2025-03-16 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tc_app', '0013_membership_profile_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('community_meetup', 'Community Meetup'), ('cultural_festival', 'Cultural Festival'), ('workshop', 'Workshop')], default='community_meetup', max_length=50),
        ),
        migrations.AlterField(
            model_name='event',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(default='Event description coming soon.'),
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(default='To be announced', max_length=200),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(default='Untitled Event', max_length=200),
        ),
    ]
