# Generated by Django 5.1.5 on 2025-03-19 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tc_app', '0014_alter_event_options_event_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='membership',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
