# Generated by Django 5.1.7 on 2025-03-19 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tc_app', '0016_default_membership_types'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='eventbooking',
            unique_together={('event', 'user')},
        ),
        migrations.AddField(
            model_name='event',
            name='capacity',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='eventbooking',
            name='booking_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.RemoveField(
            model_name='eventbooking',
            name='status',
        ),
    ]
